/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tech.skagedal.next

import com.google.api.client.json.jackson2.JacksonFactory
import java.nio.file.FileSystems

class App(
    val fileSystemLinter: FileSystemLinter,
    val intervalTaskRunner: IntervalTaskRunner,
    val gmailChecker: GmailChecker
) {
    fun run() {
        fileSystemLinter.run()
        intervalTaskRunner.run()
        gmailChecker.run()
    }
}

fun main(args: Array<String>) {
    val processRunner = ProcessRunner()
    val fileSystem = FileSystems.getDefault()
    val taskRecords = TaskRecords(fileSystem)

    val fileSystemLinter = FileSystemLinter(
        fileSystem,
        processRunner
    )
    val intervalTaskRunner = IntervalTaskRunner(
        processRunner,
        taskRecords
    )
    val gmailChecker = GmailChecker(
        fileSystem,
        processRunner,
        JacksonFactory.getDefaultInstance()
    )
    val app = App(fileSystemLinter, intervalTaskRunner, gmailChecker)

    app.run()
}
