/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tech.skagedal.next

import com.google.api.client.json.jackson2.JacksonFactory
import tech.skagedal.next.configuration.ConfigurationLoader
import tech.skagedal.next.configuration.Task
import tech.skagedal.next.configuration.TasksFile
import tech.skagedal.next.tasks.FileSystemLinterTaskFactory
import tech.skagedal.next.tasks.GmailCheckerTaskFactory
import tech.skagedal.next.tasks.IntervalTaskFactory
import java.nio.file.FileSystem
import java.nio.file.FileSystems
import java.nio.file.Files

class App(
    val fileSystem: FileSystem,
    val configurationLoader: ConfigurationLoader,
    val fileSystemLinterTaskFactory: FileSystemLinterTaskFactory,
    val intervalTaskFactory: IntervalTaskFactory,
    val gmailCheckerTaskFactory: GmailCheckerTaskFactory
) {
    fun run() {
        for (task in runnableTasks(readTasks().tasks)) {
            when (task.run()) {
                TaskResult.Proceed -> {
                }
                TaskResult.ActionRequired -> return
                is TaskResult.ShellActionRequired -> return
            }
        }
    }

    fun runnableTasks(tasks: List<Task>): List<RunnableTask> {
        return tasks.flatMap { task ->
            when (task) {
                Task.BrewUpgradeTask -> listOf(intervalTaskFactory.brewUpgradeTask())
                Task.FileSystemLintTask -> fileSystemLinterTaskFactory.standardTasks()
                is Task.GmailTask -> listOf(gmailCheckerTaskFactory.task(task.account))
            }
        }
    }

    private fun readTasks(): TasksFile {
        return Files.newBufferedReader(fileSystem.tasksYmlFile()).use { reader ->
            configurationLoader.loadTasks(reader)
        }
    }
}

fun main(args: Array<String>) {
    val processRunner = ProcessRunner()
    val fileSystem = FileSystems.getDefault()
    val taskRecords = TaskRecords(fileSystem)

    val fileSystemLinter = FileSystemLinterTaskFactory(
        fileSystem,
        processRunner
    )
    val intervalTaskRunner = IntervalTaskFactory(
        processRunner,
        taskRecords
    )
    val gmailChecker = GmailCheckerTaskFactory(
        fileSystem,
        processRunner,
        JacksonFactory.getDefaultInstance()
    )
    val app = App(fileSystem, ConfigurationLoader(), fileSystemLinter, intervalTaskRunner, gmailChecker)

    app.run()
}
